In [4]:
# Data : Using python libraries to scrap images

In [5]:
!pip install bing-image-downloader

In [6]:
!mkdir images

In [7]:
from bing_image_downloader import downloader
downloader.download("Pretty Sunflower",limit=30,output_dir="images",adult_filter_off=True)

[%] Downloading Images to /content/images/Pretty Sunflower


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://www.10wallpaper.com/wallpaper/2560x1440/1802/Pretty_sunflower_flowers_plant_closeup_2560x1440.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/originals/70/28/15/7028151ff5ce9777b8105ee3acfe2522.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://preppywallpapers.com/wp-content/uploads/2019/08/Sunflower-iPhone-Wallpapers.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i0.wp.com/texdr.wordpress.com/files/2009/07/wpid1250-img_4975.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://i.pinimg.com/originals/dd/85/81/dd8581bedcebc7d2ac327d439d792dbd.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/b9/38/b8/b938b8b361e2a573bbeee2d75799c647.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/originals/0b/e

In [34]:
downloader.download("Bikes",limit=30,output_dir="images",adult_filter_off=True)

[%] Downloading Images to /content/images/Bikes


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://p.vitalmtb.com/photos/users/26896/setup_checks/31286/photos/56839/original_DSC_0004.jpg?1469036914
[%] File Downloaded !

[%] Downloading Image #2 from https://thenewswheel.com/wp-content/uploads/2014/03/kia_electric_bike_2014.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.fullycharged.com/newsandreviews/wp-content/uploads/2016/05/Brinco-R.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i2.wp.com/www.electricbike.com/wp-content/uploads/2016/09/apex4.jpg?fit=1200%2C858&amp;ssl=1
[%] File Downloaded !

[%] Downloading Image #5 from https://p.vitalmtb.com/photos/users/44124/setup_checks/34305/photos/66328/original_Sp_Olivier_VIPBIKES_76_Modifier.jpg?1491465575
[%] File Downloaded !

[%] Downloading Image #6 from http://www.bikepacking.com/wp-content/uploads/2018/06/All-City-Gorilla-Monsoon-Review_5.jpg
[%] F

In [49]:
downloader.download("Roses",limit=30,output_dir="images",adult_filter_off=True)

[%] Downloading Images to /content/images/Roses


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://static01.nyt.com/images/2021/02/21/realestate/17garden1/17garden1-videoSixteenByNine3000-v2.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://extension.msstate.edu/sites/default/files/sg20140428_hybrid_300.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.buncombemastergardener.org/wp-content/uploads/2016/05/Roses_Tiffany_HybridTea_DiseaseResistant.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/2b/53/48/2b5348e8715afb577e401d9afdcfac6f.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://3.bp.blogspot.com/-L56PiGYzfeE/Ul0_0-Tg94I/AAAAAAAAKYE/k5yUxedd1M0/s1600/first+spring+roses+015.JPG
[%] File Downloaded !

[%] Downloading Image #6 from https://asset.bloomnation.com/c_limit,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto/v16

In [9]:
downloader.download("Icecream Cone",limit=30,output_dir="images",adult_filter_off=True)

[%] Downloading Images to /content/images/Icecream Cone


[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://cmkt-image-prd.freetls.fastly.net/0.1.0/ps/4363477/1820/2515/m1/fpnw/wm1/yopkn719kfmeteuskryzlttgadzrpqdejyql6byzkq5mti1y23tyfxcpvdhnrkqm-.jpg?1524740440&amp;s=5d2b4ad5906083aaa5736689141dfead
[!] Issue getting: https://cmkt-image-prd.freetls.fastly.net/0.1.0/ps/4363477/1820/2515/m1/fpnw/wm1/yopkn719kfmeteuskryzlttgadzrpqdejyql6byzkq5mti1y23tyfxcpvdhnrkqm-.jpg?1524740440&amp;s=5d2b4ad5906083aaa5736689141dfead
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://purepng.com/public/uploads/large/chocolate-ice-cream-cone-lwb.png
[%] File Downloaded !

[%] Downloading Image #2 from https://img-new.cgtrader.com/items/2362166/3658d8fdbc/choco-ice-cream-cone-3d-model-low-poly-obj-fbx-ma.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://static.fanpage.it/wp-content/uploads/sites/22/2018/07/coni.jpg
[%] Fil

In [35]:
# Preprocessing
# 1. resize 2. flatten
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize

data_dir='/content/images'
categories = ['Bikes','Icecream Cone','Pretty Sunflower','Roses']

flat_data=[]
target=[]

for i in categories:
  class_num=categories.index(i) #Label Encoding
  path=os.path.join(data_dir,i) # create path to use all images
  for img in os.listdir(path):
    img_array=imread(os.path.join(path,img))
    # print(img_array)
    img_resized=resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    target.append(class_num)
  
flat_data=np.array(flat_data)
target=np.array(target)

  


In [36]:
len(flat_data)

120

In [37]:
len(target)

120

In [38]:
np.unique(target)

array([0, 1, 2, 3])

In [39]:
# splitting the data into training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(flat_data,target,test_size=0.3,random_state=3)


In [40]:
# we will use SVM classifier
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1,10,100,1000],'kernel':['linear']},
              {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
]
svc = svm.SVC(probability=True)
clf= GridSearchCV(svc,param_grid)
clf.fit(x_train,y_train)

GridSearchCV(estimator=SVC(probability=True),
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}])

In [41]:
y_pred = clf.predict(x_test)
y_pred

array([1, 2, 0, 3, 3, 1, 1, 0, 3, 0, 1, 1, 0, 2, 1, 0, 1, 3, 3, 0, 0, 3,
       1, 3, 2, 2, 3, 2, 3, 0, 0, 2, 2, 3, 2, 3])

In [42]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [43]:
accuracy_score(y_pred,y_test)

0.75

In [44]:
y_test

array([3, 3, 0, 3, 3, 0, 1, 0, 3, 0, 3, 1, 3, 2, 1, 0, 1, 3, 1, 0, 0, 3,
       1, 3, 2, 2, 1, 2, 3, 0, 0, 2, 0, 3, 2, 2])

In [45]:
confusion_matrix(y_pred,y_test)

array([[8, 0, 0, 1],
       [1, 5, 0, 2],
       [1, 0, 6, 1],
       [0, 2, 1, 8]])

In [46]:
# Testing a brand new image
new_data=[]
url=input('Enter your URL')
img=imread(url)
img_resized=resize(img,(150,150,3))
new_data.append(img_resized.flatten())
new_data=np.array(new_data)
print(img.shape)
y_out=clf.predict(new_data)
print(y_out)
print(categories[y_out[0]])

Enter your URLhttps://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Strawberry_ice_cream_cone_%285076899310%29.jpg/640px-Strawberry_ice_cream_cone_%285076899310%29.jpg
(962, 640, 3)
[1]
Icecream Cone


In [48]:
print(categories)

['Bikes', 'Icecream Cone', 'Pretty Sunflower', 'Roses']
